### ISSUE TITLE
Loot Loop

### ISSUE THREAD

**Issue by Satran1000** [Satran1000/Jimtonia#3]
Noticed the looting was broken when demonstrating piece to Chelto. Whenever a loot is attempted, if it fails, the looting loops again, giving the player chance after chance till they get some loot.

**Comment by AWiseCorn** [comment]
Loot loop was fixed when we submitted, it's just you don't always get loot. only like 40/60% chance rat/ogre Respectively.

RNG's just a bitch
Fix moves the loot function to after it dies and the corpse boolean to before the RNG Check, instead of after
Still could probably give it another run over

**Comment by Satran1000** [comment]
Well now it's a different issue, but thanks for correction
