### ISSUE TITLE
Looting is not displaying message

### ISSUE THREAD

**Issue by Satran1000** [Satran1000/Jimtonia#7]
![image](https://cloud.githubusercontent.com/assets/23090903/19769029/84f32bdc-9ca5-11e6-9ac1-9825c8cad519.png)

Looting does not show result of loot, but instead shows another congratulatory message.

**Comment by Satran1000** [comment]
Been playing around a little, turns out it only doesn't display a message for ogres

**Comment by AWiseCorn** [comment]
Loot loop #2 should hopefully have fixed. c:
